builds:
  - binary: akm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
release:
  github:
    owner: ohsawa0515
    name: akm