[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "1.0.3"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/manifoldco/promptui"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"
